CREATE TABLE IF NOT EXISTS RATINGS(
	ID INT PRIMARY KEY,
	RATING_NAME VARCHAR(255),
	DESCRIPTION VARCHAR(1000)
)
ADD CONSTRAINT `ratings` FOREIGN KEY (`ID`) REFERENCES `movies` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
