CREATE TABLE IF NOT EXISTS MOVIE_SHOWTIMES(
	ID INT PRIMARY KEY,

	MOVIE_RUN_ID INT,

	MOVIE_ID INT,
	FOREIGN KEY (`MOVIE_ID`) REFERENCES `movies` (`ID`),
	THEATRE_ID INT,

	FOREIGN KEY (`THEATRE_ID`) REFERENCES `auditoriums` (`THEATRE_ID`) ON DELETE CASCADE ON UPDATE CASCADE,
	ROOM varchar(10),
	FOREIGN KEY (`ROOM`) REFERENCES `auditoriums` (`ROOM`) ON DELETE CASCADE ON UPDATE CASCADE,
	START_TIME time
	)
