CREATE TABLE IF NOT EXISTS ORDERS(
CONFIRMATION_CODE INT PRIMARY KEY,
MOVIE_SHOWTIME_ID INT,
FOREIGN KEY (`MOVIE_SHOWTIME_ID`) REFERENCES `movie_showtimes` (`ID`),
MOVIE_ID INT,
FOREIGN KEY (`MOVIE_ID`) REFERENCES `movie_showtimes` (`MOVIE_ID`),
THEATRE_ID INT,
FOREIGN KEY (`THEATRE_ID`) REFERENCES `movie_showtimes` (`THEATRE_ID`),
AUDITORIUM_ID INT,
FOREIGN KEY (`AUDITORIUM_ID`) REFERENCES `auditoriums` (`ROOM`),
ROOM varchar(10),
FOREIGN KEY (`ROOM`) REFERENCES `movie_showtimes` (`ROOM`),
START_TIME time,
FOREIGN KEY (`START_TIME`) REFERENCES `movie_showtimes` (`START_TIME`)
)
