CREATE TABLE IF NOT EXISTS ADDRESSES(
	NAME VARCHAR(255),
	LINE_1 VARCHAR(255),
	LINE_2 VARCHAR(255),
	CITY VARCHAR(255),
	FOREIGN KEY (`CITY`) REFERENCES `zip_codes` (`CITY`) ON DELETE CASCADE ON UPDATE CASCADE,
	STATE VARCHAR(255),
	FOREIGN KEY (`STATE`) REFERENCES `zip_codes` (`STATE`) ON DELETE CASCADE ON UPDATE CASCADE,
	ZIP_CODE VARCHAR(10),
	FOREIGN KEY (`ZIP_CODE`) REFERENCES `zip_codes` (`ZIP`) ON DELETE CASCADE ON UPDATE CASCADE
)
